### ISSUE TITLE
Add Refresh Button

### ISSUE THREAD

**Issue by lolchocotaco** [schauhan19/Spectatr#1]
Reload data on page by clicking the refresh button.

**Comment by csherland** [comment]
I didnt realize that you added refresh on a 60 second interval. Added a button to do it manually anyway

**Comment by lolchocotaco** [comment]
I hope it's calling the same function. >_>

**Comment by csherland** [comment]
it is

**Comment by csherland** [comment]
https://github.com/schauhan19/Spectatr/blob/master/app/App.js#L54
